"""Add HR role support and HR user

Revision ID: bd12eba79c4c
Revises: 1a2b3c4d5e66
Create Date: 2025-08-11 15:43:13.174192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd12eba79c4c'
down_revision: Union[str, None] = '1a2b3c4d5e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_employees_active_status'), table_name='hr_employees')
    op.drop_index(op.f('ix_hr_employees_department'), table_name='hr_employees')
    op.drop_index(op.f('ix_hr_employees_emp_code'), table_name='hr_employees')
    op.drop_index(op.f('ix_hr_employees_employee_id'), table_name='hr_employees')
    op.drop_index(op.f('ix_hr_employees_employment_type'), table_name='hr_employees')
    op.drop_table('hr_employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_employees',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emp_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('salary_base', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('active_status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('hr_employees_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('hr_employees_updated_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('hr_employees_user_id_fkey')),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('hr_employees_pkey'))
    )
    op.create_index(op.f('ix_hr_employees_employment_type'), 'hr_employees', ['employment_type'], unique=False)
    op.create_index(op.f('ix_hr_employees_employee_id'), 'hr_employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_employees_emp_code'), 'hr_employees', ['emp_code'], unique=True)
    op.create_index(op.f('ix_hr_employees_department'), 'hr_employees', ['department'], unique=False)
    op.create_index(op.f('ix_hr_employees_active_status'), 'hr_employees', ['active_status'], unique=False)
    # ### end Alembic commands ###
