"""Add SME Management System modules - HR, Projects, Inventory, Financial

Revision ID: f3a53b79e3bd
Revises: ea0be61f2816
Create Date: 2025-08-08 15:33:49.626174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a53b79e3bd'
down_revision: Union[str, None] = 'ea0be61f2816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
